// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPasswordHasher creates a new instance of PasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordHasher {
	mock := &PasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PasswordHasher is an autogenerated mock type for the PasswordHasher type
type PasswordHasher struct {
	mock.Mock
}

type PasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordHasher) EXPECT() *PasswordHasher_Expecter {
	return &PasswordHasher_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function for the type PasswordHasher
func (_mock *PasswordHasher) Compare(hash string, plain string) error {
	ret := _mock.Called(hash, plain)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(hash, plain)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PasswordHasher_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type PasswordHasher_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hash string
//   - plain string
func (_e *PasswordHasher_Expecter) Compare(hash any, plain any) *PasswordHasher_Compare_Call {
	return &PasswordHasher_Compare_Call{Call: _e.mock.On("Compare", hash, plain)}
}

func (_c *PasswordHasher_Compare_Call) Run(run func(hash string, plain string)) *PasswordHasher_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasswordHasher_Compare_Call) Return(err error) *PasswordHasher_Compare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PasswordHasher_Compare_Call) RunAndReturn(run func(hash string, plain string) error) *PasswordHasher_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type PasswordHasher
func (_mock *PasswordHasher) Hash(plain string) (string, error) {
	ret := _mock.Called(plain)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(plain)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(plain)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(plain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PasswordHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type PasswordHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - plain string
func (_e *PasswordHasher_Expecter) Hash(plain any) *PasswordHasher_Hash_Call {
	return &PasswordHasher_Hash_Call{Call: _e.mock.On("Hash", plain)}
}

func (_c *PasswordHasher_Hash_Call) Run(run func(plain string)) *PasswordHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PasswordHasher_Hash_Call) Return(s string, err error) *PasswordHasher_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *PasswordHasher_Hash_Call) RunAndReturn(run func(plain string) (string, error)) *PasswordHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}
