// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/nthw-dev/user-management-api/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// NewRefreshTokenRepository creates a new instance of RefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenRepository {
	mock := &RefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type RefreshTokenRepository struct {
	mock.Mock
}

type RefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenRepository) EXPECT() *RefreshTokenRepository_Expecter {
	return &RefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// FindByHash provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) FindByHash(ctx context.Context, hash string) (*app.RefreshToken, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for FindByHash")
	}

	var r0 *app.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*app.RefreshToken, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *app.RefreshToken); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RefreshTokenRepository_FindByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByHash'
type RefreshTokenRepository_FindByHash_Call struct {
	*mock.Call
}

// FindByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *RefreshTokenRepository_Expecter) FindByHash(ctx any, hash any) *RefreshTokenRepository_FindByHash_Call {
	return &RefreshTokenRepository_FindByHash_Call{Call: _e.mock.On("FindByHash", ctx, hash)}
}

func (_c *RefreshTokenRepository_FindByHash_Call) Run(run func(ctx context.Context, hash string)) *RefreshTokenRepository_FindByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_FindByHash_Call) Return(refreshToken *app.RefreshToken, err error) *RefreshTokenRepository_FindByHash_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *RefreshTokenRepository_FindByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (*app.RefreshToken, error)) *RefreshTokenRepository_FindByHash_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) Revoke(ctx context.Context, id string, now time.Time) error {
	ret := _mock.Called(ctx, id, now)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, id, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RefreshTokenRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type RefreshTokenRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - now time.Time
func (_e *RefreshTokenRepository_Expecter) Revoke(ctx any, id any, now any) *RefreshTokenRepository_Revoke_Call {
	return &RefreshTokenRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id, now)}
}

func (_c *RefreshTokenRepository_Revoke_Call) Run(run func(ctx context.Context, id string, now time.Time)) *RefreshTokenRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_Revoke_Call) Return(err error) *RefreshTokenRepository_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RefreshTokenRepository_Revoke_Call) RunAndReturn(run func(ctx context.Context, id string, now time.Time) error) *RefreshTokenRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllForUser provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) RevokeAllForUser(ctx context.Context, userID string, now time.Time) error {
	ret := _mock.Called(ctx, userID, now)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RefreshTokenRepository_RevokeAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllForUser'
type RefreshTokenRepository_RevokeAllForUser_Call struct {
	*mock.Call
}

// RevokeAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - now time.Time
func (_e *RefreshTokenRepository_Expecter) RevokeAllForUser(ctx any, userID any, now any) *RefreshTokenRepository_RevokeAllForUser_Call {
	return &RefreshTokenRepository_RevokeAllForUser_Call{Call: _e.mock.On("RevokeAllForUser", ctx, userID, now)}
}

func (_c *RefreshTokenRepository_RevokeAllForUser_Call) Run(run func(ctx context.Context, userID string, now time.Time)) *RefreshTokenRepository_RevokeAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_RevokeAllForUser_Call) Return(err error) *RefreshTokenRepository_RevokeAllForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RefreshTokenRepository_RevokeAllForUser_Call) RunAndReturn(run func(ctx context.Context, userID string, now time.Time) error) *RefreshTokenRepository_RevokeAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) Store(ctx context.Context, rt app.RefreshToken) error {
	ret := _mock.Called(ctx, rt)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.RefreshToken) error); ok {
		r0 = returnFunc(ctx, rt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RefreshTokenRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type RefreshTokenRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - rt app.RefreshToken
func (_e *RefreshTokenRepository_Expecter) Store(ctx any, rt any) *RefreshTokenRepository_Store_Call {
	return &RefreshTokenRepository_Store_Call{Call: _e.mock.On("Store", ctx, rt)}
}

func (_c *RefreshTokenRepository_Store_Call) Run(run func(ctx context.Context, rt app.RefreshToken)) *RefreshTokenRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(app.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_Store_Call) Return(err error) *RefreshTokenRepository_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RefreshTokenRepository_Store_Call) RunAndReturn(run func(ctx context.Context, rt app.RefreshToken) error) *RefreshTokenRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}
