// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nthw-dev/user-management-api/internal/app"
	"github.com/nthw-dev/user-management-api/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewUserUseCase creates a new instance of UserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUseCase {
	mock := &UserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserUseCase is an autogenerated mock type for the UserUseCase type
type UserUseCase struct {
	mock.Mock
}

type UserUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UserUseCase) EXPECT() *UserUseCase_Expecter {
	return &UserUseCase_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type UserUseCase
func (_mock *UserUseCase) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserUseCase_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type UserUseCase_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserUseCase_Expecter) Count(ctx any) *UserUseCase_Count_Call {
	return &UserUseCase_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *UserUseCase_Count_Call) Run(run func(ctx context.Context)) *UserUseCase_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserUseCase_Count_Call) Return(n int64, err error) *UserUseCase_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *UserUseCase_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *UserUseCase_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type UserUseCase
func (_mock *UserUseCase) Create(ctx context.Context, in app.CreateUserInput) (*user.User, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.CreateUserInput) (*user.User, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.CreateUserInput) *user.User); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.CreateUserInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in app.CreateUserInput
func (_e *UserUseCase_Expecter) Create(ctx any, in any) *UserUseCase_Create_Call {
	return &UserUseCase_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *UserUseCase_Create_Call) Run(run func(ctx context.Context, in app.CreateUserInput)) *UserUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.CreateUserInput
		if args[1] != nil {
			arg1 = args[1].(app.CreateUserInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserUseCase_Create_Call) Return(user1 *user.User, err error) *UserUseCase_Create_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserUseCase_Create_Call) RunAndReturn(run func(ctx context.Context, in app.CreateUserInput) (*user.User, error)) *UserUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type UserUseCase
func (_mock *UserUseCase) Delete(ctx context.Context, actorID string, id string) error {
	ret := _mock.Called(ctx, actorID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, actorID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - id string
func (_e *UserUseCase_Expecter) Delete(ctx any, actorID any, id any) *UserUseCase_Delete_Call {
	return &UserUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, actorID, id)}
}

func (_c *UserUseCase_Delete_Call) Run(run func(ctx context.Context, actorID string, id string)) *UserUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserUseCase_Delete_Call) Return(err error) *UserUseCase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserUseCase_Delete_Call) RunAndReturn(run func(ctx context.Context, actorID string, id string) error) *UserUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type UserUseCase
func (_mock *UserUseCase) Get(ctx context.Context, id string) (*user.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserUseCase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UserUseCase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserUseCase_Expecter) Get(ctx any, id any) *UserUseCase_Get_Call {
	return &UserUseCase_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *UserUseCase_Get_Call) Run(run func(ctx context.Context, id string)) *UserUseCase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserUseCase_Get_Call) Return(user1 *user.User, err error) *UserUseCase_Get_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserUseCase_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (*user.User, error)) *UserUseCase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type UserUseCase
func (_mock *UserUseCase) List(ctx context.Context, f app.ListFilter) (app.Page, error) {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 app.Page
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListFilter) (app.Page, error)); ok {
		return returnFunc(ctx, f)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListFilter) app.Page); ok {
		r0 = returnFunc(ctx, f)
	} else {
		r0 = ret.Get(0).(app.Page)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.ListFilter) error); ok {
		r1 = returnFunc(ctx, f)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserUseCase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type UserUseCase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - f app.ListFilter
func (_e *UserUseCase_Expecter) List(ctx any, f any) *UserUseCase_List_Call {
	return &UserUseCase_List_Call{Call: _e.mock.On("List", ctx, f)}
}

func (_c *UserUseCase_List_Call) Run(run func(ctx context.Context, f app.ListFilter)) *UserUseCase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.ListFilter
		if args[1] != nil {
			arg1 = args[1].(app.ListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserUseCase_List_Call) Return(page app.Page, err error) *UserUseCase_List_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *UserUseCase_List_Call) RunAndReturn(run func(ctx context.Context, f app.ListFilter) (app.Page, error)) *UserUseCase_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type UserUseCase
func (_mock *UserUseCase) Update(ctx context.Context, actorID string, id string, in app.UpdateUserInput) (*user.User, error) {
	ret := _mock.Called(ctx, actorID, id, in)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, app.UpdateUserInput) (*user.User, error)); ok {
		return returnFunc(ctx, actorID, id, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, app.UpdateUserInput) *user.User); ok {
		r0 = returnFunc(ctx, actorID, id, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, app.UpdateUserInput) error); ok {
		r1 = returnFunc(ctx, actorID, id, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserUseCase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserUseCase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - id string
//   - in app.UpdateUserInput
func (_e *UserUseCase_Expecter) Update(ctx any, actorID any, id any, in any) *UserUseCase_Update_Call {
	return &UserUseCase_Update_Call{Call: _e.mock.On("Update", ctx, actorID, id, in)}
}

func (_c *UserUseCase_Update_Call) Run(run func(ctx context.Context, actorID string, id string, in app.UpdateUserInput)) *UserUseCase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 app.UpdateUserInput
		if args[3] != nil {
			arg3 = args[3].(app.UpdateUserInput)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *UserUseCase_Update_Call) Return(user1 *user.User, err error) *UserUseCase_Update_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserUseCase_Update_Call) RunAndReturn(run func(ctx context.Context, actorID string, id string, in app.UpdateUserInput) (*user.User, error)) *UserUseCase_Update_Call {
	_c.Call.Return(run)
	return _c
}
