// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nthw-dev/user-management-api/internal/app"
	"github.com/nthw-dev/user-management-api/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type UserRepository
func (_mock *UserRepository) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type UserRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserRepository_Expecter) Count(ctx any) *UserRepository_Count_Call {
	return &UserRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *UserRepository_Count_Call) Run(run func(ctx context.Context)) *UserRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRepository_Count_Call) Return(n int64, err error) *UserRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *UserRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *UserRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type UserRepository
func (_mock *UserRepository) Create(ctx context.Context, u *user.User) error {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = returnFunc(ctx, u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - u *user.User
func (_e *UserRepository_Expecter) Create(ctx any, u any) *UserRepository_Create_Call {
	return &UserRepository_Create_Call{Call: _e.mock.On("Create", ctx, u)}
}

func (_c *UserRepository_Create_Call) Run(run func(ctx context.Context, u *user.User)) *UserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_Create_Call) Return(err error) *UserRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, u *user.User) error) *UserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type UserRepository
func (_mock *UserRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserRepository_Expecter) Delete(ctx any, id any) *UserRepository_Delete_Call {
	return &UserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *UserRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *UserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_Delete_Call) Return(err error) *UserRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *UserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type UserRepository
func (_mock *UserRepository) FindByEmail(ctx context.Context, email user.Email) (*user.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.Email) (*user.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.Email) *user.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.Email) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type UserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email user.Email
func (_e *UserRepository_Expecter) FindByEmail(ctx any, email any) *UserRepository_FindByEmail_Call {
	return &UserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *UserRepository_FindByEmail_Call) Run(run func(ctx context.Context, email user.Email)) *UserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.Email
		if args[1] != nil {
			arg1 = args[1].(user.Email)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_FindByEmail_Call) Return(user1 *user.User, err error) *UserRepository_FindByEmail_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserRepository_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email user.Email) (*user.User, error)) *UserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type UserRepository
func (_mock *UserRepository) FindByID(ctx context.Context, id string) (*user.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type UserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserRepository_Expecter) FindByID(ctx any, id any) *UserRepository_FindByID_Call {
	return &UserRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *UserRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *UserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_FindByID_Call) Return(user1 *user.User, err error) *UserRepository_FindByID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*user.User, error)) *UserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type UserRepository
func (_mock *UserRepository) List(ctx context.Context, q app.ListQuery) (app.Page, error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 app.Page
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListQuery) (app.Page, error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListQuery) app.Page); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Get(0).(app.Page)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.ListQuery) error); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type UserRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - q app.ListQuery
func (_e *UserRepository_Expecter) List(ctx any, q any) *UserRepository_List_Call {
	return &UserRepository_List_Call{Call: _e.mock.On("List", ctx, q)}
}

func (_c *UserRepository_List_Call) Run(run func(ctx context.Context, q app.ListQuery)) *UserRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.ListQuery
		if args[1] != nil {
			arg1 = args[1].(app.ListQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_List_Call) Return(page app.Page, err error) *UserRepository_List_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *UserRepository_List_Call) RunAndReturn(run func(ctx context.Context, q app.ListQuery) (app.Page, error)) *UserRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type UserRepository
func (_mock *UserRepository) Update(ctx context.Context, id string, p app.UpdatePatch) (*user.User, error) {
	ret := _mock.Called(ctx, id, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, app.UpdatePatch) (*user.User, error)); ok {
		return returnFunc(ctx, id, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, app.UpdatePatch) *user.User); ok {
		r0 = returnFunc(ctx, id, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, app.UpdatePatch) error); ok {
		r1 = returnFunc(ctx, id, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - p app.UpdatePatch
func (_e *UserRepository_Expecter) Update(ctx any, id any, p any) *UserRepository_Update_Call {
	return &UserRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, p)}
}

func (_c *UserRepository_Update_Call) Run(run func(ctx context.Context, id string, p app.UpdatePatch)) *UserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 app.UpdatePatch
		if args[2] != nil {
			arg2 = args[2].(app.UpdatePatch)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepository_Update_Call) Return(user1 *user.User, err error) *UserRepository_Update_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id string, p app.UpdatePatch) (*user.User, error)) *UserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
