#!/usr/bin/env bash
# Builds a coverage report for local review, into coverage/:
#
#   coverage/unit.out          the unit profile (the same run as `make test`, every test binary reporting every internal package)
#   coverage/integration.out   the integration profile — real MongoDB via testcontainers; skipped when Docker is not available
#   coverage/merged.out        both profiles merged: a block counts as covered when any test binary hit it
#   coverage/coverage.html     `go tool cover -html` on the merged profile, browsable file by file
#   coverage/summary.md        per-package and per-layer statement coverage, the core bar, and the least-covered functions
#
# Environment knobs:
#   SKIP_UNIT=1          reuse coverage/unit.out from an earlier run
#   SKIP_INTEGRATION=1   do not run the integration tests; an earlier coverage/integration.out is reused if present
#   MIN=80               the bar for the core (internal/domain + internal/app), the same one CI enforces
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=coverage
MIN="${MIN:-80}"
mkdir -p "$OUT"

if [[ "${SKIP_UNIT:-0}" != 1 ]]; then
  echo "== unit tests (-race, -tags dev)"
  # A failing test fails the report — the profile of a red run is not worth reading.
  go test -race -tags dev -covermode=atomic -coverpkg=./internal/... -coverprofile="$OUT/unit.out" ./...
fi

integration=skipped
if [[ "${SKIP_INTEGRATION:-0}" == 1 ]]; then
  [[ -f "$OUT/integration.out" ]] && integration="reused from an earlier run"
elif docker info >/dev/null 2>&1; then
  echo "== integration tests (-tags integration, real MongoDB via testcontainers)"
  go test -tags=integration -count=1 -covermode=atomic -coverpkg=./internal/... -coverprofile="$OUT/integration.out" ./test/...
  integration=ran
else
  echo "== Docker is not available — integration profile skipped"
  rm -f "$OUT/integration.out"
fi

# Merge: one mode line, then every block from every profile. `go tool cover` sums the counts of identical blocks.
{
  head -n 1 "$OUT/unit.out"
  for f in "$OUT/unit.out" "$OUT/integration.out"; do
    [[ -f "$f" ]] && tail -n +2 "$f"
  done
} > "$OUT/merged.out"

go tool cover -html="$OUT/merged.out" -o "$OUT/coverage.html"
go tool cover -func="$OUT/merged.out" > "$OUT/func.txt"

# Per-package and per-layer figures, computed the way scripts/check-coverage.sh computes the core:
# blocks are keyed by position, and a block counts as covered when any binary hit it.
summarize() {
  awk -v min="$MIN" -v integration="$integration" '
    function layer(pkg) {
      if (pkg ~ /\/gen\// || pkg ~ /\/apptest/) return "generated & test doubles"
      if (pkg ~ /^internal\/domain\//) return "domain"
      if (pkg ~ /^internal\/app/)      return "app (use cases)"
      if (pkg ~ /^internal\/adapter\/inbound\//)  return "inbound adapters (HTTP, gRPC, worker)"
      if (pkg ~ /^internal\/adapter\/outbound\//) return "outbound adapters (Mongo, bcrypt, JWT, clock)"
      if (pkg ~ /^internal\/platform\//) return "platform"
      return "other"
    }
    /^mode:/ { next }
    {
      key = $1; n = $2; c = $3
      split(key, a, ":"); f = a[1]
      pkg = f; sub(/\/[^\/]*$/, "", pkg); sub(/^github.com\/nthw-dev\/user-management-api\//, "", pkg)
      if (!(key in seen)) { seen[key] = 1; stmts[pkg] += n }
      if (c > 0 && !(key in hit)) { hit[key] = 1; cov[pkg] += n }
    }
    END {
      print "# Test coverage report"
      print ""
      printf "Generated by `scripts/coverage-report.sh` — integration profile: **%s**.\n", integration
      print ""
      print "Statement coverage, computed per block: a block counts as covered when any test binary (unit or integration) hit it."
      print "Generated protobuf code and the test doubles (`apptest`, `mocks`) are listed but kept out of the layer totals."
      print ""
      print "## Per layer"
      print ""
      print "| Layer | Statements | Covered | Coverage |"
      print "| --- | ---: | ---: | ---: |"
      for (p in stmts) { l = layer(p); ls[l] += stmts[p]; lc[l] += cov[p] }
      order[1] = "domain"; order[2] = "app (use cases)"; order[3] = "inbound adapters (HTTP, gRPC, worker)"
      order[4] = "outbound adapters (Mongo, bcrypt, JWT, clock)"; order[5] = "platform"; order[6] = "generated & test doubles"
      for (i = 1; i <= 6; i++) {
        l = order[i]; if (!(l in ls)) continue
        printf "| %s | %d | %d | %.1f%% |\n", l, ls[l], lc[l], 100 * lc[l] / ls[l]
        if (l != "generated & test doubles") { ts += ls[l]; tc += lc[l] }
        if (l == "domain" || l == "app (use cases)") { cs += ls[l]; cc += lc[l] }
        as += ls[l]; ac += lc[l]
      }
      printf "| **hand-written code** | %d | %d | **%.1f%%** |\n", ts, tc, 100 * tc / ts
      printf "| everything under internal/ | %d | %d | %.1f%% |\n", as, ac, 100 * ac / as
      print ""
      core = 100 * cc / cs
      printf "**Core bar** (internal/domain + internal/app, the check CI runs): %.1f%% against a minimum of %d%% — %s\n", core, min, (core + 0.0001 >= min ? "PASS" : "FAIL")
      print ""
      print "## Per package"
      print ""
      print "| Package | Statements | Covered | Coverage |"
      print "| --- | ---: | ---: | ---: |"
      # macOS awk has no asorti, so the rows go through sort(1) instead.
      for (p in stmts) printf "| %s | %d | %d | %.1f%% |\n", p, stmts[p], cov[p], 100 * cov[p] / stmts[p] | "sort"
      close("sort")
      print ""
    }
  ' "$OUT/merged.out"
}

lowest() {
  echo "## Least-covered functions (hand-written code, bottom 15)"
  echo ""
  echo "| Function | Coverage |"
  echo "| --- | ---: |"
  grep -v -e '/gen/' -e '/apptest/' -e '^total:' "$OUT/func.txt" \
    | sed 's#^github.com/nthw-dev/user-management-api/##' \
    | awk '{ printf "%s\t%s\t%s\n", $NF, $1, $2 }' \
    | sort -n | head -n 15 \
    | awk -F'\t' '{ printf "| `%s` %s | %s |\n", $2, $3, $1 }'
  echo ""
  echo "Open \`coverage/coverage.html\` for the line-by-line view."
}

{ summarize; lowest; } > "$OUT/summary.md"
cat "$OUT/summary.md"
echo
echo "report: $OUT/summary.md · $OUT/coverage.html"
